import type { IncomingMessage } from "node:http";
import { context, reddit, settings } from "@devvit/web/server";
import type { TriggerResponse } from "@devvit/web/shared";
import { once } from "node:events";
import { analyzeModmail } from "../llm.ts";
import { buildUserPrompt, type LLMResult } from "../prompts.ts";
import { getUserSummary } from "../history.ts";
import {
  checkAndMarkProcessed,
  getCachedHistory,
  incrementRateLimit,
  isOverBudget,
  isOverRateLimit,
  recordSpend,
  setCachedHistory,
} from "../cache.ts";
import { recordStats } from "../analytics.ts";

// Real shape verified against a live payload on 2026-05-23.
// Source of truth: node_modules/@devvit/protos/types/devvit/reddit/v2alpha/modmail.d.ts
type ModMailEvent = {
  conversationId: string;
  messageId: string;
  messageAuthor?: { id?: string; name?: string };
  messageAuthorType:
    | "ParticipatingAs_MODERATOR"
    | "ParticipatingAs_PARTICIPANT_USER"
    | "ParticipatingAs_PARTICIPANT_SR";
  conversationType: "internal" | "sr_user" | "sr_sr";
  conversationState: "new" | "in-progress" | "archived";
  isAutoGenerated: boolean;
  conversationSubreddit?: { id?: string; name?: string };
  destinationSubreddit?: { id?: string; name?: string };
  createdAt?: string;
  type?: "ModMail";
};

async function readJSON<T>(req: IncomingMessage): Promise<T> {
  const chunks: Uint8Array[] = [];
  req.on("data", (chunk) => chunks.push(chunk));
  await once(req, "end");
  return JSON.parse(`${Buffer.concat(chunks)}`);
}

async function postNote(conversationId: string, body: string): Promise<void> {
  // Hard Rule #1: isInternal MUST be true. Hard Rule #9: never let a failure bubble up.
  try {
    await reddit.modMail.reply({
      conversationId,
      body,
      isInternal: true,
      isAuthorHidden: false,
    });
  } catch (err) {
    console.error("[modmail-reply] failed:", err);
  }
}

function formatConfidence(c: LLMResult["confidence"]): string {
  switch (c) {
    case "high":
      return "**Draft confidence: High**";
    case "med":
      return "**Draft confidence: Medium** — review tone before sending";
    case "low":
      return "⚠️ **Draft confidence: Low** — message is ambiguous; rewrite from scratch if needed";
  }
}

function formatNote(result: LLMResult, authorName: string): string {
  const sevEmoji =
    result.severity === "high" ? "🔴" : result.severity === "med" ? "🟡" : "🟢";
  const abuseWarning = result.isAbusive
    ? "\n\n⚠️ **Mod Shield flagged this message as abusive.** You may want to skip the original and use only the draft below."
    : "";
  const quotedDraft = result.draftReply
    .split("\n")
    .map((line) => `> ${line}`)
    .join("\n");
  return [
    "### 🤖 ModMail Copilot analysis",
    "",
    `**From:** u/${authorName}`,
    `**Classification:** \`${result.classification}\``,
    `**Severity:** ${sevEmoji} ${result.severity}`,
    formatConfidence(result.confidence) + abuseWarning,
    "",
    "---",
    "",
    "**Suggested reply (copy, edit, send manually):**",
    "",
    quotedDraft,
  ].join("\n");
}

export async function onModMail(req: IncomingMessage): Promise<TriggerResponse> {
  let event: ModMailEvent;
  try {
    event = await readJSON<ModMailEvent>(req);
  } catch (err) {
    console.error("[modmail-event] failed to parse body:", err);
    return {};
  }

  console.log("[modmail-event]", JSON.stringify(event));

  // Filters — drop messages we shouldn't process. ORDER MATTERS:
  if (event.conversationType !== "sr_user") return {};
  if (event.isAutoGenerated) return {};
  if (!event.messageAuthor?.name) return {};
  // CRITICAL: skip messages WE posted, or we infinite-loop on our own internal notes.
  if (event.messageAuthor.name === context.appName) return {};
  // RESTORED in Phase 3 — skip moderator-authored modmails (no LLM cost, no draft needed):
  if (event.messageAuthorType !== "ParticipatingAs_PARTICIPANT_USER") return {};

  const conversationId = event.conversationId;
  const messageId = event.messageId;
  const authorName = event.messageAuthor.name;
  const subredditName =
    event.conversationSubreddit?.name ?? event.destinationSubreddit?.name ?? "";

  // Hard Rule #6 — idempotency: skip if we've already processed this exact message.
  try {
    if (await checkAndMarkProcessed(messageId)) return {};
  } catch (err) {
    console.error("[cache] idempotency check failed:", err);
    // Continue — better to risk a duplicate note than to silently drop a message.
  }

  // Read all settings up front
  let apiKey: string | undefined;
  let enabled = true;
  let tone: string | undefined;
  let rules: string | undefined;
  let dailyBudgetUsd = 1.0;
  try {
    apiKey = await settings.get<string>("openai-api-key");
    const enabledVal = await settings.get<boolean>("enabled");
    if (enabledVal === false) enabled = false;
    tone = (await settings.get<string[]>("tone"))?.[0];
    rules = await settings.get<string>("rules");
    const budgetVal = await settings.get<number>("daily-budget-usd");
    if (typeof budgetVal === "number" && budgetVal > 0) dailyBudgetUsd = budgetVal;
  } catch (err) {
    console.error("[settings] failed to read settings:", err);
  }

  if (!enabled) return {};

  if (!apiKey) {
    await postNote(
      conversationId,
      [
        "### 🤖 ModMail Copilot",
        "",
        "⚠️ **API key not configured.** A mod with app settings access needs to run:",
        "```",
        "devvit settings set openai-api-key",
        "```",
        "and paste the OpenAI key (`sk-...`). Please review this message manually in the meantime.",
      ].join("\n"),
    );
    return {};
  }

  // Fetch the full conversation so the LLM sees prior context, not just the latest message
  let messages: Array<{ author: string; body: string }> = [];
  try {
    const { conversation } = await reddit.modMail.getConversation({
      conversationId,
      markRead: false,
    });
    const all = Object.values(conversation?.messages ?? {});
    messages = all
      .filter((m) => !m.isInternal) // don't feed our own private notes back to the LLM
      .map((m) => ({
        author: m.author?.name ?? "unknown",
        body: m.bodyMarkdown ?? m.body ?? "",
      }))
      .filter((m) => m.body.length > 0);
  } catch (err) {
    console.error("[modmail] getConversation failed:", err);
    await postNote(
      conversationId,
      "### 🤖 ModMail Copilot\n\n⚠️ Could not read this conversation. Please review the message manually.",
    );
    return {};
  }

  if (messages.length === 0) {
    return {};
  }

  // Hard Rule #8 — per-subreddit hourly rate limit (50 calls/hr default)
  try {
    if (await isOverRateLimit(subredditName)) {
      await postNote(
        conversationId,
        "### 🤖 ModMail Copilot\n\n⚠️ **AI unavailable** (hourly limit reached). Please review manually.",
      );
      return {};
    }
  } catch (err) {
    console.error("[cache] rate limit check failed:", err);
  }

  // Hard Rule #7 — daily budget cap ($1.00 default)
  try {
    if (await isOverBudget(subredditName, dailyBudgetUsd)) {
      await postNote(
        conversationId,
        "### 🤖 ModMail Copilot\n\n⚠️ **AI unavailable** (daily budget reached). Please review manually.",
      );
      return {};
    }
  } catch (err) {
    console.error("[cache] budget check failed:", err);
  }

  // Fetch user history — check cache first (Differentiator 1)
  let userHistory: string | undefined;
  try {
    const cached = await getCachedHistory(authorName);
    if (cached) {
      userHistory = cached;
    } else {
      const fresh = await getUserSummary(authorName, subredditName);
      userHistory = fresh;
      await setCachedHistory(authorName, fresh);
    }
  } catch (err) {
    console.error("[history] getUserSummary failed:", err);
  }

  // Call Claude
  const result = await analyzeModmail(
    apiKey,
    buildUserPrompt(messages, userHistory, tone, rules),
  );
  if (!result) {
    await postNote(
      conversationId,
      "### 🤖 ModMail Copilot\n\n⚠️ **AI unavailable.** Claude returned an error or unparseable output. Please review manually.",
    );
    return {};
  }

  // Record usage after a successful LLM call
  try {
    await incrementRateLimit(subredditName);
    await recordSpend(subredditName);
    await recordStats(subredditName, result.classification, result.severity);
  } catch (err) {
    console.error("[cache] usage recording failed:", err);
  }

  // Post the structured analysis + draft
  await postNote(conversationId, formatNote(result, authorName));
  console.log(
    "[modmail-reply] posted Claude-drafted note for",
    conversationId,
    "| classification:",
    result.classification,
    "| severity:",
    result.severity,
    "| confidence:",
    result.confidence,
  );

  // Mod Shield — active escalation: ping the full mod team on high-severity or abusive messages.
  if (result.isAbusive || result.severity === "high") {
    try {
      const sevLabel = result.isAbusive ? "abusive message" : "high-severity modmail";
      await reddit.modMail.createModNotification({
        subredditId: context.subredditId,
        subject: `🛡️ Mod Shield alert — ${sevLabel} from u/${authorName}`,
        bodyMarkdown: [
          `**ModMail Copilot** detected a ${sevLabel} in [conversation ${conversationId}](https://mod.reddit.com/mail/all/${conversationId}).`,
          "",
          `**Classification:** \`${result.classification}\` | **Severity:** ${result.severity}`,
          "",
          "A private analysis note has been posted in the conversation. Please review.",
        ].join("\n"),
      });
      console.log("[mod-shield] escalation notification sent for", conversationId);
    } catch (err) {
      console.error("[mod-shield] createModNotification failed:", err);
    }
  }

  return {};
}
