import type { IncomingMessage } from "node:http";
import { context, reddit } from "@devvit/web/server";
import type { TriggerResponse } from "@devvit/web/shared";
import { once } from "node:events";

// Real shape verified against a live payload on 2026-05-23.
// Source of truth: node_modules/@devvit/protos/types/devvit/reddit/v2alpha/modmail.d.ts
type ModMailEvent = {
  conversationId: string;
  messageId: string;
  messageAuthor?: { id?: string; name?: string };
  messageAuthorType:
    | "ParticipatingAs_MODERATOR"
    | "ParticipatingAs_PARTICIPANT_USER"
    | "ParticipatingAs_PARTICIPANT_SR";
  conversationType: "internal" | "sr_user" | "sr_sr";
  conversationState: "new" | "in-progress" | "archived";
  isAutoGenerated: boolean;
  conversationSubreddit?: { id?: string; name?: string };
  destinationSubreddit?: { id?: string; name?: string };
  createdAt?: string;
  type?: "ModMail";
};

async function readJSON<T>(req: IncomingMessage): Promise<T> {
  const chunks: Uint8Array[] = [];
  req.on("data", (chunk) => chunks.push(chunk));
  await once(req, "end");
  return JSON.parse(`${Buffer.concat(chunks)}`);
}

export async function onModMail(req: IncomingMessage): Promise<TriggerResponse> {
  let event: ModMailEvent;
  try {
    event = await readJSON<ModMailEvent>(req);
  } catch (err) {
    console.error("[modmail-event] failed to parse body:", err);
    return {};
  }

  console.log("[modmail-event]", JSON.stringify(event));

  // Filter — drop messages we shouldn't process.
  if (event.conversationType !== "sr_user") return {};
  if (event.isAutoGenerated) return {};
  if (!event.messageAuthor?.name) return {};
  // CRITICAL: skip messages WE posted, or we infinite-loop on our own internal notes
  // (the app account is a mod of the sub, so its replies fire onModMail again).
  // Discovered live 2026-05-23 — see CLAUDE.md §12.
  if (event.messageAuthor.name === context.appName) return {};
  // TODO Phase 3 (re-enable before LLM call to avoid spending tokens on mod-authored messages):
  // if (event.messageAuthorType !== "ParticipatingAs_PARTICIPANT_USER") return {};

  // Hard Rule #1: isInternal MUST be true. Hard Rule #9: never let a failure bubble up.
  try {
    await reddit.modMail.reply({
      conversationId: event.conversationId,
      body: [
        "✅ **ModMail Copilot is listening.**",
        "",
        "_Phase 2 hardcoded test note — proves the trigger + internal reply work._",
        "",
        `- Author: \`u/${event.messageAuthor.name}\``,
        `- Author type: \`${event.messageAuthorType}\``,
        `- Conversation: \`${event.conversationId}\``,
        `- Message: \`${event.messageId}\``,
      ].join("\n"),
      isInternal: true,
      isAuthorHidden: false,
    });
    console.log("[modmail-reply] posted internal note for", event.conversationId);
  } catch (err) {
    console.error("[modmail-reply] failed to post note:", err);
  }

  return {};
}
